///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace US_GlobalParams
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the US_GlobalParamsRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("e236fb15-e2b4-4379-a04e-6f8b7f9de398")]
    public partial class US_GlobalParamsRepository : RepoGenBaseFolder
    {
        static US_GlobalParamsRepository instance = new US_GlobalParamsRepository();
        US_GlobalParamsRepositoryFolders.AutomatedToolsTestSiteAppFolder _automatedtoolstestsite;
        US_GlobalParamsRepositoryFolders.FormsAppFolder _forms;

        /// <summary>
        /// Gets the singleton class instance representing the US_GlobalParamsRepository element repository.
        /// </summary>
        [RepositoryFolder("e236fb15-e2b4-4379-a04e-6f8b7f9de398")]
        public static US_GlobalParamsRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public US_GlobalParamsRepository() 
            : base("US_GlobalParamsRepository", "/", null, 0, false, "e236fb15-e2b4-4379-a04e-6f8b7f9de398", ".\\RepositoryImages\\US_GlobalParamsRepositorye236fb15.rximgres")
        {
            _automatedtoolstestsite = new US_GlobalParamsRepositoryFolders.AutomatedToolsTestSiteAppFolder(this);
            _forms = new US_GlobalParamsRepositoryFolders.FormsAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("e236fb15-e2b4-4379-a04e-6f8b7f9de398")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The AutomatedToolsTestSite folder.
        /// </summary>
        [RepositoryFolder("7b0e5596-faff-4fc4-a4e2-83b1d66dab2e")]
        public virtual US_GlobalParamsRepositoryFolders.AutomatedToolsTestSiteAppFolder AutomatedToolsTestSite
        {
            get { return _automatedtoolstestsite; }
        }

        /// <summary>
        /// The Forms folder.
        /// </summary>
        [RepositoryFolder("1704861e-4eae-41a5-a802-f41f9fedf1b8")]
        public virtual US_GlobalParamsRepositoryFolders.FormsAppFolder Forms
        {
            get { return _forms; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class US_GlobalParamsRepositoryFolders
    {
        /// <summary>
        /// The AutomatedToolsTestSiteAppFolder folder.
        /// </summary>
        [RepositoryFolder("7b0e5596-faff-4fc4-a4e2-83b1d66dab2e")]
        public partial class AutomatedToolsTestSiteAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _formsInfo;

            /// <summary>
            /// Creates a new AutomatedToolsTestSite  folder.
            /// </summary>
            public AutomatedToolsTestSiteAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AutomatedToolsTestSite", "/dom[@caption='Automated Tools Test Site']", parentFolder, 30000, null, false, "7b0e5596-faff-4fc4-a4e2-83b1d66dab2e", "")
            {
                _formsInfo = new RepoItemInfo(this, "Forms", ".//div[#'menu']/ul//span[@innertext='Forms']", 30000, null, "47b04be4-862e-4f3e-b486-c345551e4693");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7b0e5596-faff-4fc4-a4e2-83b1d66dab2e")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7b0e5596-faff-4fc4-a4e2-83b1d66dab2e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Forms item.
            /// </summary>
            [RepositoryItem("47b04be4-862e-4f3e-b486-c345551e4693")]
            public virtual Ranorex.SpanTag Forms
            {
                get
                {
                    return _formsInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Forms item info.
            /// </summary>
            [RepositoryItemInfo("47b04be4-862e-4f3e-b486-c345551e4693")]
            public virtual RepoItemInfo FormsInfo
            {
                get
                {
                    return _formsInfo;
                }
            }
        }

        /// <summary>
        /// The FormsAppFolder folder.
        /// </summary>
        [RepositoryFolder("1704861e-4eae-41a5-a802-f41f9fedf1b8")]
        public partial class FormsAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _textinputInfo;
            RepoItemInfo _textareaInfo;
            RepoItemInfo _submitInfo;
            RepoItemInfo _textinputvalueInfo;
            RepoItemInfo _backtoformInfo;
            RepoItemInfo _homeInfo;

            /// <summary>
            /// Creates a new Forms  folder.
            /// </summary>
            public FormsAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Forms", "/dom[@caption='Forms']", parentFolder, 30000, null, false, "1704861e-4eae-41a5-a802-f41f9fedf1b8", "")
            {
                _textinputInfo = new RepoItemInfo(this, "TextInput", ".//input[#'textInput']", 30000, null, "ed892274-db4a-4754-ac92-64d315171447");
                _textareaInfo = new RepoItemInfo(this, "TextArea", ".//textarea[#'textArea']", 30000, null, "9b4e6a48-4e3a-46fc-a010-b7f8deec2821");
                _submitInfo = new RepoItemInfo(this, "Submit", ".//form[#'theForm']/table//a[@innertext='Submit']", 30000, null, "198a8601-4d40-41c7-8665-d38363f802ee");
                _textinputvalueInfo = new RepoItemInfo(this, "TextInputValue", ".//span[#'textInputValue']", 30000, null, "61324a0b-4aff-4de8-bf1d-0f708383e901");
                _backtoformInfo = new RepoItemInfo(this, "BackToForm", ".//div[#'formResults']/?/?/a[@innertext='Back to form']", 30000, null, "1b43575f-a351-423f-9a3b-87ca64245dd3");
                _homeInfo = new RepoItemInfo(this, "Home", ".//div[#'menu']/ul//span[@innertext='Home']", 30000, null, "af663bef-d081-43a6-a661-eba3c176c7a8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1704861e-4eae-41a5-a802-f41f9fedf1b8")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1704861e-4eae-41a5-a802-f41f9fedf1b8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TextInput item.
            /// </summary>
            [RepositoryItem("ed892274-db4a-4754-ac92-64d315171447")]
            public virtual Ranorex.InputTag TextInput
            {
                get
                {
                    return _textinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The TextInput item info.
            /// </summary>
            [RepositoryItemInfo("ed892274-db4a-4754-ac92-64d315171447")]
            public virtual RepoItemInfo TextInputInfo
            {
                get
                {
                    return _textinputInfo;
                }
            }

            /// <summary>
            /// The TextArea item.
            /// </summary>
            [RepositoryItem("9b4e6a48-4e3a-46fc-a010-b7f8deec2821")]
            public virtual Ranorex.TextAreaTag TextArea
            {
                get
                {
                    return _textareaInfo.CreateAdapter<Ranorex.TextAreaTag>(true);
                }
            }

            /// <summary>
            /// The TextArea item info.
            /// </summary>
            [RepositoryItemInfo("9b4e6a48-4e3a-46fc-a010-b7f8deec2821")]
            public virtual RepoItemInfo TextAreaInfo
            {
                get
                {
                    return _textareaInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("198a8601-4d40-41c7-8665-d38363f802ee")]
            public virtual Ranorex.ATag Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("198a8601-4d40-41c7-8665-d38363f802ee")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }

            /// <summary>
            /// The TextInputValue item.
            /// </summary>
            [RepositoryItem("61324a0b-4aff-4de8-bf1d-0f708383e901")]
            public virtual Ranorex.SpanTag TextInputValue
            {
                get
                {
                    return _textinputvalueInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The TextInputValue item info.
            /// </summary>
            [RepositoryItemInfo("61324a0b-4aff-4de8-bf1d-0f708383e901")]
            public virtual RepoItemInfo TextInputValueInfo
            {
                get
                {
                    return _textinputvalueInfo;
                }
            }

            /// <summary>
            /// The BackToForm item.
            /// </summary>
            [RepositoryItem("1b43575f-a351-423f-9a3b-87ca64245dd3")]
            public virtual Ranorex.ATag BackToForm
            {
                get
                {
                    return _backtoformInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The BackToForm item info.
            /// </summary>
            [RepositoryItemInfo("1b43575f-a351-423f-9a3b-87ca64245dd3")]
            public virtual RepoItemInfo BackToFormInfo
            {
                get
                {
                    return _backtoformInfo;
                }
            }

            /// <summary>
            /// The Home item.
            /// </summary>
            [RepositoryItem("af663bef-d081-43a6-a661-eba3c176c7a8")]
            public virtual Ranorex.SpanTag Home
            {
                get
                {
                    return _homeInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Home item info.
            /// </summary>
            [RepositoryItemInfo("af663bef-d081-43a6-a661-eba3c176c7a8")]
            public virtual RepoItemInfo HomeInfo
            {
                get
                {
                    return _homeInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
